name: approve-and-fast-forward-merge-pr
on: pull_request
jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-approve pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
      
      - name: fast-forward pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const latestCommitSHA = context.payload.pull_request.head.sha;

            await github.rest.git.updateRef({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              ref: `heads/${context.payload.pull_request.base.ref}`,
              sha: latestCommitSHA,
              force: false
            }); 
